MINUTE_IN_TIME_STAMP =60
HOUR_IN_TIME_STAMP = MINUTE_IN_TIME_STAMP * 60 
DAY_IN_TIME_STAMP = HOUR_IN_TIME_STAMP * 24 
WEEK_IN_TIME_STAMP = DAY_IN_TIME_STAMP * 7 
MONTH_IN_TIME_STAMP = WEEK_IN_TIME_STAMP * 4
YEAR_IN_TIME_STAMP = MONTH_IN_TIME_STAMP * 12